name: ActionsWorkflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: php-actions/composer@v6
    - run: vendor/bin/phpunit Tests/
